#PAIR_SYMBOLS = ["BTCUSDT","ETHUSDT","BNBUSDT"]
PAIR_SYMBOLS = ["BTCUSDT","ETHUSDT"]
BALANCE_SYMBOLS = ["USDT","BTC","ETH","BNB"]

TIME_LENGTH = 100
CHECKPOINT_PATH = "TrainData/checkpoint_TimeLength{time_length:03d}.ckpt"

